/** Etiquetas visibles en español para códigos internos (API / enums). */

export const SYSTEM_STATUS_ES: Record<string, string> = {
  NOMINAL: "Nominal",
  ALERT: "Alerta",
  OFFLINE: "Sin conexión",
  WATCH: "Vigilancia",
};

export const STATUS_ES: Record<string, string> = {
  ...SYSTEM_STATUS_ES,
  ACTIVE: "Activo",
  INACTIVE: "Inactivo",
  PENDING: "Pendiente",
  REJECTED: "Rechazado",
  APPROVED: "Aprobado",
  OPEN: "Abierto",
  CLOSED: "Cerrado",
  DONE: "Cerrado",
  IN_PROGRESS: "En curso",
  WAITING_PARTS: "Esperando repuestos",
  AVAILABLE: "Disponible",
  IN_SERVICE: "En servicio",
  MAINTENANCE: "En taller",
  OUT_OF_SERVICE: "Fuera de servicio",
  COMPLIANCE_BLOCKED: "Bloqueado por documentos",
  VALID: "Vigente",
  EXPIRED: "Vencido",
  EXPIRING: "Por vencer",
  GREEN: "Verde",
  YELLOW: "Amarillo",
  AMBER: "Ámbar",
  RED: "Rojo",
  RED_0: "Rojo",
  VACATION: "Vacaciones",
  MEDICAL: "Incapacidad",
  ASSIGNED: "Asignado",
  IN_TRANSIT: "En ruta",
  COMPLETED: "Terminado",
  CANCELLED: "Cancelado",
  INCIDENT: "Novedad",
  ON_LOAN: "En préstamo",
  BACKLOG: "Pendiente",
  DRAFT: "Borrador",
  WON: "Ganada",
  LOST: "Perdida",
  OFF: "Inactivo",
  N_A: "N/A",
  SENT: "Enviada",
  REQUESTED: "Solicitada",
  ORDERED: "Ordenada",
  QUOTED: "Cotizada",
  ISSUED: "Emitida",
  PAID: "Pagada",
  UNPAID: "Pendiente de pago",
  OVERDUE: "Vencida",
  LOCKED: "Cerrado",
  SEALED: "Sellado",
  MATCHED: "Cuadrado",
  UNMATCHED: "Sin cruzar",
  RECEIVED: "Recibida",
  VALIDATING_DOCS: "Validando documentos",
  CONTRACT_SIGN: "Firma de contrato",
  ACTIVE_FLEET: "Activo en flota",
  WAITING: "En espera",
  CHECKED_IN: "Ingresó",
  CHECKED_OUT: "Salió",
  NEW: "Nuevo",
  RESOLVED: "Resuelto",
  ESCALATED: "Escalado",
  SCHEDULED: "Programado",
  DELAYED: "Retrasado",
  BLOCKED: "Bloqueado",
  HEALTHY: "Sano",
  DEGRADED: "Degradado",
  CRITICAL: "Crítico",
  RUNNING: "En ejecución",
  STOPPED: "Detenido",
  SUCCESS: "Correcto",
  FAILED: "Fallido",
  ERROR: "Error",
  OK: "Correcto",
  WARNING: "Advertencia",
  INFO: "Información",
  LOW: "Bajo",
  MEDIUM: "Medio",
  HIGH: "Alto",
  URGENT: "Urgente",
  IDLE: "En espera",
  BUSY: "Ocupado",
  ONLINE: "En línea",
  CONNECTED: "Conectado",
  DISCONNECTED: "Desconectado",
  PUBLISHED: "Publicado",
  UNPUBLISHED: "Sin publicar",
  ARCHIVED: "Archivado",
  SUSPENDED: "Suspendido",
  ENABLED: "Habilitado",
  DISABLED: "Deshabilitado",
  TRUE: "Sí",
  FALSE: "No",
  VOID: "Anulado",
  FLAGGED: "Marcado",
  CLEARED: "Liberado",
  DISPATCH_BLOCKED: "Despacho bloqueado",
  HARD_STOP: "Bloqueo operativo",
  LOW_STOCK: "Stock bajo",
  EMAIL: "Correo",
  WHATSAPP: "WhatsApp",
  PHONE: "Teléfono",
  WEB: "Web",
  B2B: "Empresa",
  ESCOLAR: "Escolar",
  TURISMO: "Turismo",
  ADMIN: "Administrativo",
};

export function statusEs(raw: string | null | undefined): string {
  if (raw == null || raw === "") return "—";
  const key = String(raw).trim();
  return STATUS_ES[key] || STATUS_ES[key.toUpperCase()] || key;
}

export function systemStatusEs(raw: string | null | undefined): string {
  if (!raw) return "Nominal";
  return SYSTEM_STATUS_ES[raw] || SYSTEM_STATUS_ES[String(raw).toUpperCase()] || raw;
}
