/** Códigos de Hard-Stop / Compliance Gate — Módulo 04 Logística */
export const COMPLIANCE_BLOCK_CODES = {
  VEHICLE_NOT_FOUND: "VEHICLE_NOT_FOUND",
  DRIVER_NOT_FOUND: "DRIVER_NOT_FOUND",
  VEHICLE_COMPLIANCE_BLOCKED: "VEHICLE_COMPLIANCE_BLOCKED",
  VEHICLE_OUT_OF_SERVICE: "VEHICLE_OUT_OF_SERVICE",
  VEHICLE_MAINTENANCE: "VEHICLE_MAINTENANCE",
  VEHICLE_NIGHT_RESTRICTED: "VEHICLE_NIGHT_RESTRICTED",
  SOAT_EXPIRED: "SOAT_EXPIRED",
  SOAT_MISSING: "SOAT_MISSING",
  TECNOMECANICA_EXPIRED: "TECNOMECANICA_EXPIRED",
  TECNOMECANICA_MISSING: "TECNOMECANICA_MISSING",
  FUEC_EXPIRED: "FUEC_EXPIRED",
  FUEC_MISSING: "FUEC_MISSING",
  DRIVER_DISPATCH_BLOCKED: "DRIVER_DISPATCH_BLOCKED",
  DRIVER_INACTIVE: "DRIVER_INACTIVE",
  DRIVER_FATIGUE: "DRIVER_FATIGUE",
  DRIVER_LICENSE_EXPIRED: "DRIVER_LICENSE_EXPIRED",
  DRIVER_LICENSE_MISSING: "DRIVER_LICENSE_MISSING",
  DRIVER_NIGHT_RESTRICTED: "DRIVER_NIGHT_RESTRICTED",
} as const;

export type ComplianceBlockCode =
  (typeof COMPLIANCE_BLOCK_CODES)[keyof typeof COMPLIANCE_BLOCK_CODES];

export type ComplianceViolation = {
  code: ComplianceBlockCode;
  message: string;
  entity?: "vehicle" | "driver" | "document";
  entityId?: string;
  detail?: Record<string, unknown>;
};

export type ComplianceGateResult = {
  ok: true;
} | {
  ok: false;
  violations: ComplianceViolation[];
};
